[[redirects]]
from = "/example"
to = "https://example.com"
status = 301
force = true

[[redirects]]
from = "/fb"
to = "https://facebook.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/facebook"
to = "https://facebook.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/github"
to = "https://github.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/instagram"
to = "https://instagram.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/linkedin"
to = "https://linkedin.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/medium"
to = "https://medium.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/stackexchange"
to = "https://stackexchange.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/stackoverflow"
to = "https://stackoverflow.dimuththarindu.com"
status = 301
force = true
