[[redirects]]
from = "/example"
to = "https://example.com"
status = 301
force = true

[[redirects]]
from = "/fb"
to = "https://facebook.dimuththarindu.com"
status = 301
force = true

[[redirects]]
from = "/facebook"
to = "https://facebook.dimuththarindu.com"
status = 301
force = true
